<?php

namespace AppBundle\Repository;

/**
 * ActionsMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionsMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
