<?php

namespace AppBundle\Repository;

/**
 * ActionsMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\Entityrepository;


class ActionsMatchRepository extends EntityRepository
{
    /**public function PassesStats()
     * {
     * $dql = 'SELECT c.joueurReceveur FROM AppBundle:ActionsMatch c WHERE c.joueurReceveur = 0';
     * $query = $this->getEntityManager()->createQuery($dql);
     * return $query->execute();
     * }
     *
     * public function PassesAmis()
     * {
     * $dql = 'SELECT c.joueurReceveur FROM AppBundle:ActionsMatch c WHERE c.joueurReceveur > 0';
     * $query = $this->getEntityManager()->createQuery($dql);
     * return $query->execute();
     * }**/

    /**Perte passes equipe 1**/
    public function PassesAmisPerdues()
    {
        $dql = 'SELECT c FROM AppBundle:ActionsMatch c WHERE c.joueurAction > 0 AND c.actionId = 0 AND c.joueurReceveur = 0';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    }

    /** passes reussies equipe 1**/
    public function PassesAmisReussies()
    {
        $dql = 'SELECT c FROM AppBundle:ActionsMatch c WHERE c.joueurAction > 0 AND c.actionId = 0 AND c.joueurReceveur > 0';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    }

    /**Perte passes equipe 2**/
    public function PassesEnnemiesPerdues()
    {
        $dql = 'SELECT c FROM AppBundle:ActionsMatch c WHERE c.joueurAction = 0 AND c.actionId = 0 AND c.joueurReceveur > 0';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    }

    public function PassesEnnemiesReussies()
    {
        $dql = 'SELECT c FROM AppBundle:ActionsMatch c WHERE c.joueurAction = 0 AND c.actionId = 0 AND c.joueurReceveur = 0';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    }

}
