<?php

namespace AppBundle\Repository;

/**
 * EntraineursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntraineursRepository extends \Doctrine\ORM\EntityRepository
{
}
