# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_denied_url: /

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path:            /coach
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: / #This is home url
            anonymous:    true

            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/register, allow_if: "not has_role('ROLE_USER')"}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coach, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/equipes, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/joueurs, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/clavier, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/statsmatch, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/cpa, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/possession, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/tirs, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/avantMatch, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/recuperation, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/listeMatch, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/listeEquipe, role: IS_AUTHENTICATED_REMEMBERED }
